# Basic `dependabot.yml` file with
# minimum configuration for three package managers

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep Python dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-dev-tools:
        patterns:
          - "black"
          - "flake8"
          - "isort"
          - "pre-commit"
          - "pytest"
          - "pytest-*"
          - "coverage"
          - "pytest-cov"
          - "build"
      python-build-system:
        patterns:
          - "setuptools"
          - "wheel"
      python-runtime:
        patterns:
          - "typing_extensions"
